spring.application.name=kitchen

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
app.cors.allowed-origins=${APP_FRONTEND_URL:http://localhost:3000}

spring.main.allow-bean-definition-overriding=true
app.jwt.secret=${JWT_SECRET}
app.jwt.expirationMinutes=60

ocr.api.key=${OCR_API_KEY}
spoonacular.base-url=https://api.spoonacular.com
spoonacular.api-key=${SPOONACULAR_API_KEY}

spring.devtools.restart.enabled=false

management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/
management.endpoint.health.show-details=never

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB

app.rate-limit.default=60
app.rate-limit.auth-login=5
