spring.application.name=kitchen

spring.datasource.url=jdbc:h2:tcp://localhost/C:/H2/bin/Kitchen
spring.datasource.username=hexhax
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.driverClassName=org.h2.Driver
spring.sql.init.mode=always