spring.application.name=kitchen

spring.datasource.url=jdbc:postgresql://nozomi.proxy.rlwy.net:37610/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=KGLAeaOOnXFTNDLaKhQmzEsIDUXpFxqe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
app.cors.allowed-origins=${APP_FRONTEND_URL:http://localhost:3000}

spring.main.allow-bean-definition-overriding=true
app.jwt.secret=${APP_JWT_SECRET:TpFvhuTjMGY3TzQGna0F7jpL8xDi9SDuic8DMIT3Uijbuiqoj3Vm5acZJZpGqAKdwV8lgx5ZVjWYpw0KQ9SbyA==}
app.jwt.expirationMinutes=60